default:
  image:
    name: registry.gitlab.com/orica/deployments/docker-images/dockerpython
    
include: 
  - project: 'orica/registry/ci-templates'
    ref: master
    file: /get-vault-assume-role.yml

stages:
  - plan
  - apply
  - addaccount

tf_plan:
  tags:
    - aws-apac-docker
  stage: plan
  environment:
    name: production
  extends:
    - .get-assume-role
  script:
    - terraform init
    - terraform plan -out=tf.plan
  artifacts:
    paths:
      - tf.plan
  when: manual
  only:
    refs:
      - master
    changes:
      - "*.tf"

# Separate apply job for manual launching Terraform as it can be destructive
# action.
tf_apply:
  tags:
    - aws-apac-docker
  stage: apply
  environment:
    name: production
  extends:
    - .get-assume-role
  script:
    - terraform init
    - terraform apply -input=false -auto-approve -no-color tf.plan
  dependencies:
    - tf_plan
  when: manual
  only:
    refs:
      - master
    changes:
      - "*.tf"
  
# Separate apply job for manual adding aws account into LM
# action.
add_account:
  tags:
    - aws-apac-docker
  stage: addaccount
  environment:
    name: production
  extends:
    - .get-assume-role
  script:
    - python2 AddAccount/lm-addaccount.py $accountid $lmdevicename
  when: manual
  only:
    # refs:
    #   - master
    changes:
      - AddAccount/*.py


